---

postgres_rhel8_repo: pgdg-redhat-repo-latest
postgres_packages:
    - postgresql14
    - postgresql14-server 
    - postgresql14-contrib 
    - postgresql14-libs
postgres_library: "python3-psycopg2"
postgres_10_data_dir: /var/lib/pgsqldata
postgres_port: 5432