---
- name: 01 Infra Provision | Provision Openstack servers
  hosts: localhost
  vars_files:
    - vars/main-vars.yml
  tasks:
    - name: 01 Infra Provision | Get control node facts from Openstack
      os_server_info:
        cloud: "{{ instance_cloud | default(omit) }}"
        server: control
      register: control_node_info
    
    - name: 01 Infra Provision | Provision load-balancer instance
      include_role:
        name: os_instance
      vars:
        instance_name: demo-lb
        instance_ns: "{{ control_node_info.openstack_servers[0].private_v4 }}"
        instance_metadata: "AnsibleGroup=load_balancers,deployment_name=demo"

    - name: 01 Infra Provision | Provision database instance
      include_role:
        name: os_instance
      vars:
        instance_name: demo-db
        instance_ns: "{{ control_node_info.openstack_servers[0].private_v4 }}"
        instance_metadata: "AnsibleGroup=database_servers,deployment_name=demo"
    
    - name: 01 Infra Provision | Provision Webserver-1 instance
      include_role:
        name: os_instance
      vars:
        instance_name: demo-web1
        instance_ns: "{{ control_node_info.openstack_servers[0].private_v4 }}"
        instance_metadata: "AnsibleGroup=app_servers,deployment_name=demo"
    
    - name: 01 Infra Provision | Provision Webserver01 instance
      include_role:
        name: os_instance
      vars:
        instance_name: demo-web2
        instance_ns: "{{ control_node_info.openstack_servers[0].private_v4 }}"
        instance_metadata: "AnsibleGroup=app_servers,deployment_name=demo"
