---
- import_playbook: 00-in-memory-inventory.yml

- name: 03 Database | Deploy, configure, and populate Postgres
  hosts: database_servers
  become: true
  gather_facts: false
  roles:
    - postgresql