---
- import_playbook: 00-in-memory-inventory.yml

- name: 05 Load Balancers | Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false 
  become: true
  roles:
    - 05-setup-load-balancer