---
- import_playbook: 00-in-memory-inventory.yml

- name: 07 Smoke Tests | End to end smoke tests
  hosts: app_servers:database_servers
  gather_facts: true
  become: true
  tasks:
    - name: 07 Smoke Tests | DB | Smoketest Postgres database
      postgresql_ping:
        db: flask_db
        login_host: "{{ hostvars['demo-db'].ansible_host }}"
        login_user: flask
        login_password: redhat
        ssl_mode: disable
      delegate_to: "{{ groups.app_servers[0] }}"
      run_once: true
      tags:
        - smoketest

- name: 07 Smoke Tests | End to end smoke tests
  hosts: app_servers
  become: false
  gather_facts: false
  tasks:
    - name: 07 Smoke Tests | Webserver | Check webserver for correct response
      uri:
        url: "http://{{ hostvars['demo-lb'].ansible_host }}/ping"
        return_content: yes
      until: '"alive" in result.content'
      retries: 10
      delay: 1
      register: result
      delegate_to: localhost