---
- name: 08 Teardown | Infrastructure | Cleanup infra resources
  hosts: control
  vars_files:
    - vars/main-vars.yml
  tasks:
    - name: 08 Teardown | Infrastructure | 
      os_server_info:
        cloud: "{{ instance_cloud | default(omit) }}"
        server: dev-*
      register: dev_instances_info

    - name: 08 Teardown | Infrastructure | 
      os_server:
        cloud: "{{ instance_cloud | default(omit) }}"
        name: "{{ __instance.name }}"
        state: absent
      loop: "{{ dev_instances_info.openstack_servers }}"
      loop_control:
        loop_var: __instance