---
# defaults file for postgresql
postgres_rhel8_repo: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
postgres_packages:
  - postgresql14
  - postgresql14-server 
  - postgresql14-contrib 
  - postgresql14-libs
postgres_library: python3-psycopg2
postgres_data_dir: /var/lib/pgsql/data
postgres_bin_path: /usr/pgsql-14/bin
postgres_service: postgresql.service
postgres_port: 5432
postgres_user: postgres
postgres_users:
  - name: flask
    password: redhat
    database: flask_db
    state: present
    priv: ALL
postgres_databases:
  - name: flask_db
    owner: flask
  - name: books_store
    owner: flask